version: '3'

services:
  mongo-example:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - network-test

  api-student-example:
    image: m4sterin/api-student:latest
    ports:
      - "4000:4000"
    networks:
      - network-test
    links:
      - mongo-example
    depends_on:
      - mongo-example

networks:
  network-test:
    driver: bridge